module.exports = {
  User: require("./User"),
  EmailOTP: require("./EmailOTP"),
  Project: require("./Project"),
  ProjectDocument: require("./ProjectDocument"),
  FundingRound: require("./FundingRound"),
  Favorite: require("./Favorite"),
  InvestorInterest: require("./InvestorInterest"),
  ESGCriteria: require("./ESGCriteria"),
  ProjectESGEvaluation: require("./ProjectESGEvaluation"),
  ESGScore: require("./ESGScore"),
  ProjectView: require("./ProjectView"),
  Notification: require("./Notification"),
  Report: require("./Report"),
  AdminLoginLog: require("./AdminLoginLog"),
  AuditLog: require("./AuditLog"),
  AdminFaceProfile: require("./AdminFaceProfile"),
  Message: require("./Message"),
  Comment: require("./Comment"),
};